version: '3'
services:
  crawling-service:
    image: saladtechnologies/crawling-service:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - HOST=0.0.0.0
      - AWS_DEFAULT_REGION=us-east-2
      - AWS_PROFILE=crawler-service
      - S3_BUCKET_NAME=salad-crawler-page-data
      - CRAWL_TABLE_NAME=crawls
      - PAGES_TABLE_NAME=pages
    volumes:
      - ~/.aws:/root/.aws
